"""baml_client — the auto-generated BAML client stubs.

Auto-generated by `baml-cli generate` (per the
`tuatha/baml/*.baml` contracts). Manually-written stub here
because `baml-cli` is not installed in the parent's venv.

The real generator output is `baml_client.sync_client.baml` etc.;
this stub provides the canonical `b` singleton + the b
context manager for the Python code.
"""
from __future__ import annotations

import asyncio
import json
from typing import Any, Callable


class _Stub:
    """The canonical BAML stub that satisfies `from baml_client import b`."""

    def __init__(self) -> None:
        self.calls: list[tuple[str, dict[str, Any]]] = []

    async def GenerateMathSyllabus(self, *, lo_code: str, level: str, language: str) -> dict[str, Any]:
        self.calls.append(("GenerateMathSyllabus", {"lo_code": lo_code, "level": level, "language": language}))
        return {"ncca_code": lo_code, "title_en": "", "title_ga": "", "description_en": "", "description_ga": "", "source_pdf": "", "source_page": 0}

    async def GenerateMathPastPaper(self, *, year: int, level: str, paper: int) -> dict[str, Any]:
        return {"year": year, "level": level, "paper": paper, "paper_url": ""}

    async def GenerateMathMarkingScheme(self, *, lo_code: str, level: str, year: int) -> dict[str, Any]:
        return {"lo_code": lo_code, "level": level, "year": year, "scheme_url": "", "criteria": []}

    async def GenerateMathFormativeItem(self, *, lo_code: str, difficulty: int, level: str, topic: str, evidence: str = "") -> dict[str, Any]:
        return {"lo_code": lo_code, "difficulty": difficulty, "level": level, "multiple_choice": "", "short_answer": "", "extended_response": "", "evidence": evidence}

    async def ScoreMathFormativeResponse(self, *, item_id: str, student_response: str, response_format: str, time_taken_seconds: int, hints_used: int) -> dict[str, Any]:
        return {"item_id": item_id, "student_response": student_response, "grade": 0.0, "feedback_en": "", "feedback_ga": "", "badge_emitted": False}

    async def GenerateAppliedMathematicsSyllabus(self, **kwargs): return await self.GenerateMathSyllabus(**kwargs)
    async def GenerateAppliedMathematicsPastPaper(self, **kwargs): return await self.GenerateMathPastPaper(**kwargs)
    async def GenerateAppliedMathematicsMarkingScheme(self, **kwargs): return await self.GenerateMathMarkingScheme(**kwargs)
    async def GenerateAppliedMathematicsFormativeItem(self, **kwargs): return await self.GenerateMathFormativeItem(**kwargs)
    async def ScoreAppliedMathematicsFormativeResponse(self, **kwargs): return await self.ScoreMathFormativeResponse(**kwargs)
    async def GenerateChemistrySyllabus(self, **kwargs): return await self.GenerateMathSyllabus(**kwargs)
    async def GenerateChemistryPastPaper(self, **kwargs): return await self.GenerateMathPastPaper(**kwargs)
    async def GenerateChemistryMarkingScheme(self, **kwargs): return await self.GenerateMathMarkingScheme(**kwargs)
    async def GenerateChemistryFormativeItem(self, **kwargs): return await self.GenerateMathFormativeItem(**kwargs)
    async def ScoreChemistryFormativeResponse(self, **kwargs): return await self.ScoreMathFormativeResponse(**kwargs)
    async def GenerateGeographySyllabus(self, **kwargs): return await self.GenerateMathSyllabus(**kwargs)
    async def GenerateGeographyPastPaper(self, **kwargs): return await self.GenerateMathPastPaper(**kwargs)
    async def GenerateGeographyMarkingScheme(self, **kwargs): return await self.GenerateMathMarkingScheme(**kwargs)
    async def GenerateGeographyFormativeItem(self, **kwargs): return await self.GenerateMathFormativeItem(**kwargs)
    async def ScoreGeographyFormativeResponse(self, **kwargs): return await self.ScoreMathFormativeResponse(**kwargs)
    async def GenerateHistorySyllabus(self, **kwargs): return await self.GenerateMathSyllabus(**kwargs)
    async def GenerateHistoryPastPaper(self, **kwargs): return await self.GenerateMathPastPaper(**kwargs)
    async def GenerateHistoryMarkingScheme(self, **kwargs): return await self.GenerateMathMarkingScheme(**kwargs)
    async def GenerateHistoryFormativeItem(self, **kwargs): return await self.GenerateMathFormativeItem(**kwargs)
    async def ScoreHistoryFormativeResponse(self, **kwargs): return await self.ScoreMathFormativeResponse(**kwargs)
    async def GenerateEnglishSyllabus(self, **kwargs): return await self.GenerateMathSyllabus(**kwargs)
    async def GenerateEnglishPastPaper(self, **kwargs): return await self.GenerateMathPastPaper(**kwargs)
    async def GenerateEnglishMarkingScheme(self, **kwargs): return await self.GenerateMathMarkingScheme(**kwargs)
    async def GenerateEnglishFormativeItem(self, **kwargs): return await self.GenerateMathFormativeItem(**kwargs)
    async def ScoreEnglishFormativeResponse(self, **kwargs): return await self.ScoreMathFormativeResponse(**kwargs)
    async def GenerateGaeilgeSyllabus(self, **kwargs): return await self.GenerateMathSyllabus(**kwargs)
    async def GenerateGaeilgePastPaper(self, **kwargs): return await self.GenerateMathPastPaper(**kwargs)
    async def GenerateGaeilgeMarkingScheme(self, **kwargs): return await self.GenerateMathMarkingScheme(**kwargs)
    async def GenerateGaeilgeFormativeItem(self, **kwargs): return await self.GenerateMathFormativeItem(**kwargs)
    async def ScoreGaeilgeFormativeResponse(self, **kwargs): return await self.ScoreMathFormativeResponse(**kwargs)
    async def GenerateComputerScienceSyllabus(self, **kwargs): return await self.GenerateMathSyllabus(**kwargs)
    async def GenerateComputerSciencePastPaper(self, **kwargs): return await self.GenerateMathPastPaper(**kwargs)
    async def GenerateComputerScienceMarkingScheme(self, **kwargs): return await self.GenerateMathMarkingScheme(**kwargs)
    async def GenerateComputerScienceFormativeItem(self, **kwargs): return await self.GenerateMathFormativeItem(**kwargs)
    async def ScoreComputerScienceFormativeResponse(self, **kwargs): return await self.ScoreMathFormativeResponse(**kwargs)

    async def MarkingGrader(self, **kwargs): return {"response": "marking_grader stub"}
    async def AdaptiveTutor(self, **kwargs): return {"response": "adaptive_tutor stub"}
    async def EquivalencyGenerator(self, **kwargs): return {"response": "equivalency_generator stub"}

    async def ExtractComicDescriptor(self, **kwargs): return {"work": kwargs.get("work", ""), "medium": "comic", "language": kwargs.get("language", "en"), "source_url": kwargs.get("source_url", ""), "source_timestamp": str(kwargs.get("source_page", "")), "power_event": "", "visual_grammar": "", "palette": "", "vfx_vocabulary": "", "narrative_beat": "", "transferability": "", "provenance": "", "shippable": False}
    async def ExtractProseDescriptor(self, **kwargs): return {**await self.ExtractComicDescriptor(**kwargs), "medium": "prose"}
    async def ExtractAnimationDescriptor(self, **kwargs): return {**await self.ExtractComicDescriptor(**kwargs), "medium": "animation"}
    async def ExtractGameplayDescriptor(self, **kwargs): return {**await self.ExtractComicDescriptor(**kwargs), "medium": "gameplay"}
    async def ExtractOfficialDocumentDescriptor(self, **kwargs): return {**await self.ExtractComicDescriptor(**kwargs), "medium": "official"}


b = _Stub()
